server:
  port: 8080

error:
  include-message: always


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: ismaelDev
    password: password
  flyway:
      baselineOnMigrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Corrected typo in dialect
        format_sql: true
    show-sql: true

main:
  web-application-type: servlet
